### ISSUE TITLE
Stuttering when changing Audio volume on the actual machine

### ISSUE THREAD

**Issue by peteh** [GioF71/squeezelite-docker#101]
I'm running on a ryzen 5800x with a Asus Xonar DX in pulse audio mode. 
When changing the volume on the machine (on the actual machine using keyboard volume up, not just on the web interface of the server), the player starts stuttering until I restart the machine (just restarting the docker container seems not to resolve the issue)

Maybe it would also be beneficial to be able to change the logging settings from the container. Seems like no logs are actually shown after starting squeezelite

I also tried mounting the pulse cookie but the issue is the same with or without it. 

Docker compose file: 
```
version: "3"

services:
  squeezelite-super-amazing-dac:
    image: giof71/squeezelite:stable
    container_name: squeezelite-super-amazing-dac
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PRESET=super-amazing-dac,archimago-goldilocks,rates_up_to_384k
      - SQUEEZELITE_NAME=super-amazing-dac
      - SQUEEZELITE_SERVER_PORT=192.168.2.50
      - DISPLAY_PRESETS=Y
      - SQUEEZELITE_MODE=PULSE
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ${HOME}/.pulse:/root/.pulse 
```

```
pete@lokalhorst2:~$ cat /proc/asound/cards
 0 [DX             ]: AV200 - Xonar DX
                      Asus Virtuoso 100 at 0xd000, irq 39
 1 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xfc080000 irq 119
```

```
pete@lokalhorst2:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: DX [Xonar DX], device 0: Multichannel [Multichannel]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: DX [Xonar DX], device 1: Digital [Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 11: HDMI 5 [HDMI 5]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: NVidia [HDA NVidia], device 12: HDMI 6 [HDMI 6]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

```
pete@lokalhorst2:~$  aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
sysdefault
    Default Audio Device
iec958
    IEC958 (S/PDIF) Digital Audio Output
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=DX,DEV=0
    Xonar DX, Multichannel
    Direct hardware device without any conversions
hw:CARD=DX,DEV=1
    Xonar DX, Digital
    Direct hardware device without any conversions
plughw:CARD=DX,DEV=0
    Xonar DX, Multichannel
    Hardware device with all software conversions
plughw:CARD=DX,DEV=1
    Xonar DX, Digital
    Hardware device with all software conversions
sysdefault:CARD=DX
    Xonar DX, Multichannel
    Default Audio Device
front:CARD=DX,DEV=0
    Xonar DX, Multichannel
    Front output / input
surround21:CARD=DX,DEV=0
    Xonar DX, Multichannel
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=DX,DEV=0
    Xonar DX, Multichannel
    4.0 Surround output to Front and Rear speakers
surround41:CARD=DX,DEV=0
    Xonar DX, Multichannel
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=DX,DEV=0
    Xonar DX, Multichannel
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=DX,DEV=0
    Xonar DX, Multichannel
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=DX,DEV=0
    Xonar DX, Multichannel
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=DX,DEV=0
    Xonar DX, Multichannel
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=DX,DEV=0
    Xonar DX, Multichannel
    Direct sample mixing device
dmix:CARD=DX,DEV=1
    Xonar DX, Digital
    Direct sample mixing device
usbstream:CARD=DX
    Xonar DX
    USB Stream Output
hw:CARD=NVidia,DEV=3
    HDA NVidia, HDMI 0
    Direct hardware device without any conversions
hw:CARD=NVidia,DEV=7
    HDA NVidia, HDMI 1
    Direct hardware device without any conversions
hw:CARD=NVidia,DEV=8
    HDA NVidia, HDMI 2
    Direct hardware device without any conversions
hw:CARD=NVidia,DEV=9
    HDA NVidia, HDMI 3
    Direct hardware device without any conversions
hw:CARD=NVidia,DEV=10
    HDA NVidia, HDMI 4
    Direct hardware device without any conversions
hw:CARD=NVidia,DEV=11
    HDA NVidia, HDMI 5
    Direct hardware device without any conversions
hw:CARD=NVidia,DEV=12
    HDA NVidia, HDMI 6
    Direct hardware device without any conversions
plughw:CARD=NVidia,DEV=3
    HDA NVidia, HDMI 0
    Hardware device with all software conversions
plughw:CARD=NVidia,DEV=7
    HDA NVidia, HDMI 1
    Hardware device with all software conversions
plughw:CARD=NVidia,DEV=8
    HDA NVidia, HDMI 2
    Hardware device with all software conversions
plughw:CARD=NVidia,DEV=9
    HDA NVidia, HDMI 3
    Hardware device with all software conversions
plughw:CARD=NVidia,DEV=10
    HDA NVidia, HDMI 4
    Hardware device with all software conversions
plughw:CARD=NVidia,DEV=11
    HDA NVidia, HDMI 5
    Hardware device with all software conversions
plughw:CARD=NVidia,DEV=12
    HDA NVidia, HDMI 6
    Hardware device with all software conversions
hdmi:CARD=NVidia,DEV=0
    HDA NVidia, HDMI 0
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=1
    HDA NVidia, HDMI 1
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=2
    HDA NVidia, HDMI 2
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=3
    HDA NVidia, HDMI 3
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=4
    HDA NVidia, HDMI 4
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=5
    HDA NVidia, HDMI 5
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=6
    HDA NVidia, HDMI 6
    HDMI Audio Output
dmix:CARD=NVidia,DEV=3
    HDA NVidia, HDMI 0
    Direct sample mixing device
dmix:CARD=NVidia,DEV=7
    HDA NVidia, HDMI 1
    Direct sample mixing device
dmix:CARD=NVidia,DEV=8
    HDA NVidia, HDMI 2
    Direct sample mixing device
dmix:CARD=NVidia,DEV=9
    HDA NVidia, HDMI 3
    Direct sample mixing device
dmix:CARD=NVidia,DEV=10
    HDA NVidia, HDMI 4
    Direct sample mixing device
dmix:CARD=NVidia,DEV=11
    HDA NVidia, HDMI 5
    Direct sample mixing device
dmix:CARD=NVidia,DEV=12
    HDA NVidia, HDMI 6
    Direct sample mixing device
usbstream:CARD=NVidia
    HDA NVidia
    USB Stream Output
```

**Comment by GioF71** [comment]
Hello @peteh,
one thing you might try is to avoid to use `/dev/snd` for this container: it is not needed for pulseaudio mode.
I do not believe that this might be the issue, but it's probably worth mentioning anyway.
Also, the PRESETS are not applied in PulseAudio mode. They are not considered and do not contribute to the composition of the command line. 

About the logging: it's squezelite running after I create the command line, so I don't have a lot of control after the initial phase.
However, I might add support for the `-d` option and enable more verbose logging.

Also, can you add the container logs to the issue?
You most probably already know how to do it but anyway:

`docker-compose logs`

Thank you.

**Comment by GioF71** [comment]
I also tried with my (very old) Acer Aspire 5750g with no issue. I am using Manjaro KDE, and I tried changing the main PulseAudio volume, and also changing the volume in LMS.
No stuttering.
Is my scenario similar to yours? Of course I am using the onboard audio with this laptop, in pulse mode for the squeezelite container. 

Let's see what happens when you remove `/dev/snd`.

Cheers!

**Comment by GioF71** [comment]
Opened [issue 102](https://github.com/GioF71/squeezelite-docker/issues/102) for log level support.

**Comment by peteh** [comment]
@GioF71 I tried commenting out the /dev/snd but the behavior didnt change. I also tried to double the buffer size without any impact. It looks like the buffer is not passed to the command line though

Logs: 
```
pete@lokalhorst2:~/Programming/docker/squeezebox-lite$ docker logs squeezelite-super-amazing-dac 
Setting default value for STARTUP_DELAY_SEC: [0]
About to sleep for 0 second(s)
Ready to start.
Using PULSE mode
Running in pulse mode
Setting default value for PUID: [1000]
Setting default value for PGID: [1000]
Home directory [/home/sq-pulse] not found, creating.
drwxr-xr-x 2 1000 1000 4096 Oct  1 11:58 /home/sq-pulse
total 8
drwxr-xr-x 2 1000 1000 4096 Oct  1 11:58 .
drwxr-xr-x 1 root root 4096 Oct  1 11:58 ..
group sq-pulse does not exist, creating...
user sq-pulse does not exist, creating...
uid=1000(sq-pulse) gid=1000(sq-pulse) groups=1000(sq-pulse),29(audio)
user sq-pulse created.
cat /app/assets/pulse-client-template.conf
# Connect to the host's server using the mounted UNIX socket
default-server = unix:/run/user/PUID/pulse/native

# Prevent a server running in the container
autospawn = no
daemon-binary = /bin/true

# Prevent the use of shared memory
enable-shm = false
Creating pulseaudio configuration file /etc/pulse/client.conf...
# Connect to the host's server using the mounted UNIX socket
default-server = unix:/run/user/1000/pulse/native

# Prevent a server running in the container
autospawn = no
daemon-binary = /bin/true

# Prevent the use of shared memory
enable-shm = false
Initializing command line: [/usr/bin/squeezelite -o pulse]
Variable SQUEEZELITE_SERVER_PORT has been specified: 192.168.2.50
Variable SQUEEZELITE_NAME has been specified: "Living Room Computer"
Command Line: [/usr/bin/squeezelite -o pulse -s 192.168.2.50 -n "Living Room Computer"]
```

**Comment by GioF71** [comment]
Yes only a few parameters are usable in pulseaudio mode.
Would it be possible for you to run a natively installed squeezelite binary from the terminal, using the same command line options and report the results of the test?

Thank you

**Comment by peteh** [comment]
That's a great idea, then we can check if it's a general issue. Which binary are you using in the docker container? Then I can maybe install the same version.

**Comment by GioF71** [comment]
I would start with what is available in the repos of your distro. Or from those available on source forge. The links are in the install.sh file of the repo!

**Comment by GioF71** [comment]
I would start with what is available in the repos of your distro. Or from those available on source forge. The links are in the install.sh file of the repo!

Btw, which version of the image are you using? Is it updated?

Ps I see it is the stable version. Just ensure to download the last version of the image with

docker pull giof71/squeezelite:stable

**Comment by GioF71** [comment]
Hello, I double-checked that I am also using the stable tag on my laptop with no issue.
Also, can you try using the onboard audio instead of the audio card, and see if the issue persists?
One other this, you might want to keep dmesg monitoring active using this on a terminal:

`watch 'dmesg | tail -n 20'`

**Comment by GioF71** [comment]
And, last thing, you could verify your uid and gid with

`uid`

from the terminal and specify PUID and PGID env variables accordingly.

**Comment by peteh** [comment]
**Running on Ubuntu**

I tried ubuntu's own version on the host installed with apt-get: Squeezelite v1.9.9-1395, Copyright 2012-2015 Adrian Smith, 2015-2021 Ralph Irving. (Build options: LINUX PULSEAUDIO EVENTFD RESAMPLE FFMPEG VISEXPORT IR DSD SSL LINKALL)

Which has a separate binary called squeezelite-pulse, `-o pulse` does not work for this binary however it is using pulse. This does not show the issues as seen from the docker container. So we can exclude a hardware issue (and therefore onboard audio does not necessarily need to be tested - i have it disabled and bios and wired everything to the card, so I'd like to not mess with that). 

**UID GUID**

uid and gid is 1000, so this is ok too. Also set it in docker compose now but does not change the behavior. 

**DMESG**

In dmesg there are no particular outputs at the time stamps when the issue occurs (in fact there are none that point to audio devices at all). 

**Next ideas?**

Next step I'll try is to run the binary from the docker container on the host with the same parameters. If this works we can pinpoint it down to the setup in the docker container and how we pass pulse to it. 

Good approach or do you have other suggestions?

**Comment by GioF71** [comment]
Mostly a good strategy.
Before messing with binaries, I would try one among the ":jammy", ":latest" and ":edge" versions of the image.
The jammy version is probably exactly the same you the squeezelite binary from your distro.
The latest and edge are versions from debian bullseye (1.9.8) and debian wookworm (1.9.9) respectively.

Let me know how those work for you

**Comment by GioF71** [comment]
Uhm maybe I found something interesting.
All the binaries on my images do not have the "PULSEAUDIO" build option. But they work on my systems, I do not know why. But the binary you installed has been build with this option. If you installed squeezelite-pulse, maybe try with the vanilla version and see if you can reproduce the issue.

**Comment by GioF71** [comment]
Hello, unfortunately the regular versions do not support pulseaudio.
See [here](https://packages.debian.org/source/bullseye/squeezelite) and [here](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=squeezelite&searchon=names).
For some reasons the images work in pulseaudio mode on my manjaro desktops.

Let's see if the other versions I suggested you work, otherwise maybe I can build a version for you to test with ubuntu:jammy as base package and squeezelite-pulse installed (and executed as well). 
If the packages are not exclusive, I might install both of them and run the correct one based on environment variables.

**Comment by GioF71** [comment]
try with this image:

giof71/squeezelite:feature-101-stuttering-build01-jammy-squeezelite-1.9.9

It contains both binaries and runs the pulseaudio version.

**Comment by peteh** [comment]
This works, no stuttering anymore! I'll now try if this also resolves the issue on my raspberry pi setup when using the usb dac.

**Comment by GioF71** [comment]
Amazing news.
Thischabge is also on main versions now. You can use the "jammy" version for example

**Comment by peteh** [comment]
Yep already tried on the pi as well. 
Living Room Pi with onboard audio: 
 - Rhasspy and Squeezebox can play music/voice at the same time

Office Pi with USB DAC: 
 - Rhasspy and Squeezebox works (before it was just stuttering when starting) but I cannot do voice and music at the same time, maybe something is messed up with the pulse audio setup for rhasspy there

But for now I think the issue can be considered closed using the jammy version

**Comment by GioF71** [comment]
Actually i am installing both, in the middle i copy the binaries to /app/bin
Yes unfortunately they are mutually exclusive

**Comment by GioF71** [comment]
I just tested squeezelite in pulseaudio mode (image with the `latest` tag) on my desktop, it worked great with youtube playing audio at the same time.

**Comment by GioF71** [comment]
Hello @peteh, can we close this issue?
If there are further things to do, we can always create a new one.
Thank you.

**Comment by peteh** [comment]
Yes for now I'm happy and it's working so far
