### ISSUE TITLE
How to turn off the mixer aka volume at 100%

### ISSUE THREAD

**Issue by sangju41** [GioF71/squeezelite-docker#241]
Hello,

I would like to turn off the volume control and always output at 100% level.

I think it should be enabled by setting the SQUEEZELITE_UNMUTE env variable.
What would be the approprite value for it ?

Document says it's same as -U option of the squeezelite command. 
According to squeezelite document -U option takes <control> as its value.
I could not find what exactly the <control> format is.

So, how would I set the volume control off ?

Thanks in advance.

**Comment by sangju41** [comment]
Sorry for the trouble. 
I found it should be set from LMS player -> Audio Settings.

**Comment by GioF71** [comment]
Thank you for the feedback. Please report if there is something I should change or maybe mention in the documentation.
Cheers
